### ISSUE TITLE
problem with visualisation example code gemeenten at coasts

### ISSUE THREAD

**Issue by jan-perl** [ObjectVision/GeoDMS#143]
I used sample code from 
https://github.com/ObjectVision/GeoDMS/wiki/CBS-gemeente-wijk-buurt-kaart

combined with a background layer
https://github.com/jan-perl/EPcheck/blob/main/cfg/EPcheck/ngr_layer.dms

and
	container Geography // Define the extend of the scene and the projection 
	{
		unit<fpoint> rdc_base : format = "EPSG:28992", DialogData = "ngr_layer";               // Rijksdriehoekstelsel, a 2D cartesian coordinate system for the netherlands
		unit<fpoint> rdc_meter      := range(rdc_base, point(0f, 300000f), point(280000f, 625000f)); // Define a 2D range consisting of 2D cartesian coordinates, later used for the "province" domain unit geometry attribute
		unit<fpoint> rdc      := Geography/rdc_meter;

		#include<ngr_layer.dms>                                                                // Tiles for background layer
	}

the code

			unit<uint32> gemeentekoppchkcbs := unique(SourceData/CBS_2022/gemeenten/Gemeentenaam ) 
			,    StorageName = "%ProjDir%/output/kchk-cbs.dbf" 
			{
			    attribute<string>     gemeentenaamd   := string( Values);	  
				attribute<Geography/rdc> geometry (polygon) := SourceData/CBS_2022/Gemeenten/geometry[gem_geo_idx];
				attribute<ratio>  test         := float32(rnd_uniform(0, ., range(float32, 0f, 1f)));
            }

yield a picture that is distorted at the coasts:

![testrnd1](https://user-images.githubusercontent.com/4221882/218692850-0bc68e33-8208-450e-95df-182a32dad8ca.jpg)

**Comment by mtbeek32** [comment]
The issue here is that multiple municipalities occur multiple times in the municipality table, usually with a water polygon and a non-water  polygon. This applies mainly to he municipalities at the coast.

The selection can be made with the H2O attribute.

With the unique(SourceData/CBS_2022/gemeenten/Gemeentenaam ) calculation rule, I assume you want to have a table at the municipalities level. My advice is to change this expression into:

unit<uint32> gemeentekoppchkcbs :=  
select_many(SourceData/CBS_2022/gemeenten,  SourceData/CBS_2022/gemeenten/H20 == 'NEE').

The subitems do not have to be configured.

**Comment by jan-perl** [comment]
Thanks. I fixed it in another way.

      unit<uint32> gemeenten: StorageName = "%ProjDir%/data/WijkBuurtkaart_2022_v1/WijkBuurtkaart_2022_v1/gemeente_2022_v1.shp"
      ,  StorageType     = "gdal.vect"
      ,	 StorageReadOnly = "True"
      {
         attribute<Geography/rdc> geometry (polygon);
		 // compatibility with GPKG names
		 attribute<string> Gemeentenaam := GM_NAAM + iif(H2O =='NEE','','_water');
      }
	  
I can include this in the sample code at
https://github.com/ObjectVision/GeoDMS/wiki/CBS-gemeente-wijk-buurt-kaart

**Comment by mtbeek32** [comment]
Ik denk dat de opties zo voldoende duidelijk zijn
