### ISSUE TITLE
.gdb Permission denied

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#17]
In extra versie van 8.6.3. gemaakt door Erik op 6 januari geeft errors op alle .gdb's

GDAL Error: cannot open dataset D:/SourceData/Overig/Stads_en_Dorpsgezichten_2020.gdb D:/SourceData/Overig/Stads_en_Dorpsgezichten_2020.gdb: Permission denied

OVSRV6:
C:\ProjDir\Jip\Verdichting_issueGH17\cfg\verdichting.dms
/Brondata/Overig/StadsDorpsGezichten_src

**Comment by eoudejans** [comment]
Issue confirmed, is reproducible.

**Comment by eoudejans** [comment]
Gdal version 3.5.3 used for build of temporary version. Newest available version from dependency manager vcpkg is gdal 3.6.2. Retrying to see if issue is resolved. As a sidenote: gdal 3.6.0 is retracted due to possible index corruption when writing a geopackage file with > 1e5 entries, see [](https://github.com/OSGeo/gdal/releases).

**Comment by eoudejans** [comment]
The experimental GeoDMS version that caused this issue contained a change in GDAL storage manager logic that attempted to cleverly select the right driver for the dataset based on filename extension. This mechanism did not work as intended and caused exotic datasets like pbf to be read by even weirder niche drivers like the GPSBabel driver. Resolved from commit [0f16d606a9451c614c42e9da223161c5b85bcdca]https://github.com/ObjectVision/GeoDMS/commit/0f16d606a9451c614c42e9da223161c5b85bcdca), thus fixed in the upcoming GeoDMS releases.

**Comment by basvanbemmel** [comment]
Ik krijg deze melding weer in 20.10.0

<img width="1920" height="1040" alt="Image" src="https://github.com/user-attachments/assets/7b813c84-44f8-4b0b-8b99-1ac9e9227381" />

**Comment by MaartenHilferink** [comment]
@jipclaassens Kun jij eens kijken of je dit .gdb issue kunt reproduceren met 20.10.0 en of t niet ook te reproduceren is met 20.9.0 of de laatste release 20.8.0 ?

**Comment by jipclaassens** [comment]
@basvanbemmel er komen wat vragen op:
- heb je dit ook in 20.8.0?
- bij een verse opening van geodms, of na een reload?
- heb je de gdb ook open in QGIS oid?

**Comment by basvanbemmel** [comment]
Ik heb het kunnen oplossen door de gdb te openen en opnieuw te exporteren naar gdb in ArcGisPro
Wel goed om te vermelden dat het om een gdb ging van bijna 10 jaar oud. Wellicht anders weggeschreven in die tijd wat niet meer goed in te lezen is.

Ja ook in 20.8.0
Neen niet in QGIS (geen locking dus)

<img width="1920" height="1200" alt="Image" src="https://github.com/user-attachments/assets/8fdf664d-3b4d-4055-be82-8a5cc8b5a8b2" />

zowel na reload als vers openen

<img width="1920" height="1200" alt="Image" src="https://github.com/user-attachments/assets/ff27972d-df59-4b90-8a10-f2456b613545" />

**Comment by MaartenHilferink** [comment]
@basvanbemmel Als je wil dat we het openen van de 10 jaar oude .gdb verder onderzoeken, kun je die dan hier toevoegen of in source data zetten of mailen? Issue sluiten kan ook.

Inschatting: de GeoDMS leest .gbd's via https://gdal.org/en/stable/drivers/vector/avcbin.html  Het is voor ons lastig om hier veel aan te doen en ik verwacht deze driver in casu niet tot ander gedrag dan niet openen aan te kunnen zetten.

We zouden wellicht ook FileGDBAPI.dll, beschikbaar gesteld door ESRI onder Apache 2.0 license kunnen gebruiken door daar een eigen storage manager voor te schrijven: werktijd ongeveer 1 week, maar ik ben daar geen voorstander van aangezien ik begrepen heb dat zowel het .gbd formaat als de genoemde .dll closed source zijn.

**Comment by basvanbemmel** [comment]
ik sluit het issue, heel generiek ben ik ook meer voostander van gpkg formaat.

**Comment by MaartenHilferink** [comment]
Hier nog van background info: https://chatgpt.com/share/6a7d850c-37e4-83eb-8c2a-706c90a182a0
