### ISSUE TITLE
ConfigDetailPage should have a scrollbar and functioning navigation when truncated.

### ISSUE THREAD

**Issue by MaartenHilferink** [ObjectVision/GeoDMS#217]
Desired functionality: when text in detailpage is truncated, a vertial and/or horizontal scroll bar should be drawn, up, dn, left, right, PgUp, PgDn should work similar to the mouse-scroll wheel, especially since my laptop doesn't have such wheel. 
STR: see #215

**Comment by eoudejans** [comment]
Fixed in commit https://github.com/ObjectVision/GeoDMS/commit/50cf44bed9757de1b39d6f6f3765f48928728453. 
Added scrollbar navigation when content in detail pages does not fit the content region. See:
 
![issue_217_dp_navigation_scrollbar](https://user-images.githubusercontent.com/96182097/235670501-e42d720f-67f3-4243-b0dd-f7ba0bd7f76c.png)
