### ISSUE TITLE
sum_uint64 does not work over float64 values

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#312]
OVSRV06:
`C:\ProjDir\Jip\_Github_issues\TowardsAnUrbanPreview_UrbanDensity_issueGH312\cfg\stam.dms`

`/Preprocessing/Urban/Population_R2023_Create/Y2010/Population`

**Comment by MaartenHilferink** [comment]
When I click on that item, I get:
/Preprocessing/Urban/Population_R2023_Create/Y2010/Population

**Comment by MaartenHilferink** [comment]
However, in the code I see that sum_float(xx) are defined for all numeric object arguents, but that sum_(u)int(xx) is only defined for integer types. This is intentional, as the type suffix indicates the accumulator per partition, and rounding to nearest integer per element is not a likely use case. Is `sum(uint64(floatdata), partition_rel)` indeed intended? Or did you need to express `uint64(sum(floatdata, partition_rel))` or `uint64(sum_float64(floatdata, partition_rel))` here ?
