### ISSUE TITLE
unexpected export path

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/GeoDMS#392]
Steps to reproduce:

GeoDMS 12.1.0, QT Gui,

repository: https://github.com/ObjectVision/GeoDMS-Test
Configuration file: ..\tst\Unit\Storage\cfg\write_gdal_csv.dms

Export primary data on item: /export

Suggested name: E:/LocalData/ObjectVision/export, where does ObjectVision comes from?

related to issue https://github.com/ObjectVision/GeoDMS/issues/390

**Comment by eoudejans** [comment]
The base path for suggested export filename should be the expanded %localDataProjDir%. The expansion required for context the to be exported treeitem. This was given as an empty string, which caused the expansion function to add current dir in the mix because "" was found to not be an absolute path.
Fixed, see:



![export_primary_data_weird_naming](https://github.com/ObjectVision/GeoDMS/assets/96182097/d88a0f24-111f-4acc-a1ba-2ebaeb6920c7)
