### ISSUE TITLE
CreateView Error: Cannot create view with style 5 with context '/Desktops/Default/View0'

### ISSUE THREAD

**Issue by basvanbemmel** [ObjectVision/GeoDMS#398]
when activating /ConfigSettings (which isnt configured) I get pop window with

![image](https://github.com/ObjectVision/GeoDMS/assets/24241780/1db327f5-27a6-4e34-ba14-a75ceeed6a0d)
with message:
CreateView Error: Cannot create view with style 5 with context '/Desktops/Default/View0'

https://pbl.sliksvn.com/ruimtescanner/PBL/ProjDir/branches/Cursus_MartijnSpoon

**Comment by eoudejans** [comment]
In case the user requests the default view for an item (double click, treeview context menu), the default viewstyle of the current item is determined. In case of ConfigSettings, the default viewstyle could not be deduced, but the create view logic was continued nonetheless.

I adjusted the logic for default view requests in these special cases to issue an error message instead of an error dialog, see:
![default_view_configsettings](https://github.com/ObjectVision/GeoDMS/assets/96182097/ff8a5b28-b497-4515-9395-ca244e11c3be)

Closing comment as implemented, @basvanbemmel feel free to reopen when solution is insufficient.
