### ISSUE TITLE
configuring to a WMTS server does result in an unclear error

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/GeoDMS#431]
a warning with ... is not informative, see following screendump:

![image](https://github.com/ObjectVision/GeoDMS/assets/24246911/360e124a-f68c-42c5-accb-c66148605fb6)

Steps to reproduce:

- GeoDMS 12.2.0, Qt
- configuration: https://svn6.sliksvn.com/objectvisi_acc/CityCo 
- revision: 98

1) first request item: Wroclaw/prepare_basedata/make_fss  in table view.
2) Reopen configuration
3) Edit Config Source on item: Geometries/WebMercator, set DialogData = "tms_layer_osm_webmercator_gisco" and save configuration. 
4) Request item: Wroclaw/road/geometry_WM in MapView. Warning with ... occurs.

**Comment by mtbeek32** [comment]
![Image](https://github.com/ObjectVision/GeoDMS/assets/24246911/b4963a22-ad2f-4ef6-83e5-6d477dbd5560)

Issue with .. is now solved :)

Remaining specific issues:
- error does not indicate which host is unknown
- error is colored as a warning, but a host unknown should be an error
- category is not progress but connection

related issue:

**Comment by eoudejans** [comment]
When adding the DataItem as layer to a mapview, Boost::Asio is unable to resolve the host (https to ip). There is a try-catch block error handling mechanism around the addLayer function for the Mapview. This is, possibly amongst other reasons, in place because no uncaught exception may enter Qts eventloop.
This does mean that because Boost::Asio throws an exception, the error is handled at point of the addLayer to Mapview.

This is now changed and I added additional error handling specifically to the Boost::Asio resolver stage, which now signifies an error to the end user as follows, with the correct message category:
![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/87b5eba1-380c-49d7-b06f-df30bf2fd8b4)

**Comment by mtbeek32** [comment]
Hoi Erik,

Zou je eens kunnen kijken of dit request bij jou werkt:

https://gisco-services.ec.europa.eu/maps/tiles/OSMCartoV4Background/EPSG3857/13/4195/2747.png

groetjes,

Martin

________________________________
Van: eoudejans ***@***.***>
Verzonden: donderdag 21 september 2023 15:42
Aan: ObjectVision/GeoDMS ***@***.***>
CC: Martin van der Beek ***@***.***>; Author ***@***.***>
Onderwerp: Re: [ObjectVision/GeoDMS] configuring to a WMTS server does result in an unclear error (Issue #431)


When adding the DataItem as layer to a mapview, Boost::Asio is unable to resolve the host (https to ip). There is a try-catch block error handling mechanism around the addLayer function for the Mapview. This is, possibly amongst other reasons, in place because no uncaught exception may enter Qts eventloop.
This does mean that because Boost::Asio throws an exception, the error is handled at point of the addLayer to Mapview.

This is now changed and I added additional error handling specifically to the Boost::Asio resolver stage, which now signifies an error to the end user as follows, with the correct message category:
[image]<https://user-images.githubusercontent.com/96182097/269632649-87b5eba1-380c-49d7-b06f-df30bf2fd8b4.png>

**Comment by jipclaassens** [comment]
If a task is moved to done, please close it. Or it isn't done?
