### ISSUE TITLE
connections and requests are shown in the eventlog, while in the filter they are not checked 

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/GeoDMS#438]
![image](https://github.com/ObjectVision/GeoDMS/assets/24246911/62f9a6d5-a22c-4113-810b-dbe096e662ee)

**Comment by eoudejans** [comment]
This behavior is unwanted, and results from a bug in message (re) filter logic. Turning both connection and request filters off makes the minor/major trace determine if this specific log message should be shown or not. As solution I will implement a minor rewrite in order to separate logic between type and catergory filters.
