### ISSUE TITLE
unbalanced placeholder crash

### ISSUE THREAD

**Issue by mtbeek32** [ObjectVision/GeoDMS#452]
Steps to reproduce, to be added

**Comment by mtbeek32** [comment]
GeoDms 13.0.0 
tst project
configuration: tst\Unit\Other\cfg\unbalanced_placeholder_crash.dms
expand item vastgoed

**Comment by eoudejans** [comment]
Further investigation it seems that an error is thrown from Qt's event handler:

Error: [[/vastgoed/pand]] GetFullStorageName('WaardenlandSourceDataDir%/BAG/20230101/pand.fss'): unbalanced placeholder delimiters (%).Exception thrown at 0x00007FFD9E27CF19 in GeoDmsGuiQt.exe: Microsoft C++ exception: DmsException at memory location 0x0000007F1FFF3068.
Exception thrown at 0x00007FFD9E27CF19 in GeoDmsGuiQt.exe: Microsoft C++ exception: DmsException at memory location 0x0000007F1FFF3B18.
Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt.
You must not let any exception whatsoever propagate through Qt code.

**Comment by eoudejans** [comment]
Fixed in latest commit, an error was thrown while requesting additional information during painting. This is necessary to determine if the treeitem has a storage to show the storage icon in treeview. However in case an error is thrown here, this was not handled. Implemented proper handling of the error.

![unhandled_error_issue_452](https://github.com/ObjectVision/GeoDMS/assets/96182097/af09dacf-6c9a-4b64-b763-95e55d803901)

Closing issue as fixed.
