### ISSUE TITLE
Formatering value info

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#569]
1. uitlijning 1: nu heb je rekenregel dan witregel, dan tabel met resultaat en dan direct de volgende rekenregel. Beter die witregel na de tabel doen ipv ervoor.
2. uitlijning 2: wellicht werken met inspringen

![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/4d17a6a8-c132-4bb5-8d69-03bbbe0e59a6)

**Comment by eoudejans** [comment]
Rework of value info formatting resulted in:
- 1) proper grouping of value info levels
- 2) indentation per explain level (up to level 3)

See:

![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/71a9d0dd-1c30-4f0a-820e-77fdd4bd46a3)

Suggestion 3 is of valid concern but needs more thinking on how to implement, mostly because it requires the full scope of all to be explained items and their names.

**Comment by jipclaassens** [comment]
Related for 3: #418

**Comment by eoudejans** [comment]
Added bullet points to indentation for clarity purposes. See:
![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/a6ef87c5-3bf4-4bc3-b724-859f8086ff06)
