### ISSUE TITLE
Bring Icon-Pan back in GUI

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#593]

**Comment by eoudejans** [comment]
(re)Implemented pan icon to Mapview, see:

![Image](https://github.com/ObjectVision/GeoDMS/assets/96182097/462f2e1b-5760-4e9b-8167-0b6480839974)

Closing as implemented.

**Comment by basvanbemmel** [comment]
v14.7.0? of de nog uit te geven 14.8.0?

**Comment by jipclaassens** [comment]
After clicking, for example, the zoom-tool and then unclicking zoom. It should enable the pan-tool again, right? 

Now the behaviour is there, but not the enabling of the button.

**Comment by basvanbemmel** [comment]
@Jip: mij niet duidelijk of de opmerking nu gaat over een versie waar ik nu nog niet bij kan?
"After clicking" in versie?

**Comment by jipclaassens** [comment]
> @jip: mij niet duidelijk of de opmerking nu gaat over een versie waar ik nu nog niet bij kan? "After clicking" in versie?

Het handje is nu standaard ingedrukt, als je vervolgens op de zoomknop drukt, en dan nog eens op de zoom. Dan is er niets meer ingedrukt. Terwijl het gedrag van handje nog wel actueel is. Erik gaat het knop gedrag nog even bekijken.

**Comment by eoudejans** [comment]
Fixed in latest commit, mapview tools are now working like radio buttons, with the additional behavior that the pan tool is the default active tool. When the zoom tool is deactivated, the pan tool becomes reactivated, signalling the user that panning is the modus operandi for mouse drags on the map.

Closing issue as finalized, can always be reopened if needed.
