### ISSUE TITLE
Herinlezen van tif waarvan de extent onjuist wordt gemapped

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#635]
![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/aaadd102-ee0b-4195-8b85-3f398d0f83a7)

OVSRV6:
`C:\ProjDir\Jip\_Github_issues\2BURP_issueGH635\cfg\main.dms`

Open item:
`/Preprocessing/UrbanArea/UrbanArea_StartYear/GridData`

Tiff has values, we see that in QGIS.

**Comment by eoudejans** [comment]
A minimal reproducible example of the data read is created and can be found on OVSRV07 at D:\SourceData\2BURB\cfg.

The issue when rereading the data is twofold:
- The projection can not be retrieved from domain as dialog data
- GridData instead of ReadData is used
- The background layer disappears during config reload events using ie. alt-r

The following code does read the proper extend of Europe in this case:
```
unit<ipoint> read_data
:   StorageName = "D:/SourceData/2BURB/data/IsUrban_Y1990_1000m_Threshold-0_2.tif" 
,   StorageType = "gdal.grid"
,   StorageReadOnly = "True"
,   DialogData  = "Geography/LatLong_Base" //latlon" 
{    
	 attribute<float32> GridData;    
	 attribute<float32> ReadData (Geography/domain);
}
```

This lead to the situation where a reproducible scenario is found for the wms background layer disappearing after reloading the configuration. Where in GraphDataView.cpp line ~148 the dialog data property was read from a cached previously read configuration. Which causes the wms background layer to only load the first startup, and not at follow up reloads.

As solution (WIP) both dialog data and spatial reference are encoded and consequently decoded in the newly added function WorldCrdUnit->GetBackgroundReference() to retrieve the proper background reference and no longer rely on the misuse of m_BackRef item, which pointed to dms files read in previous startups of GeoDMS.

**Comment by jipclaassens** [comment]
![image](https://github.com/ObjectVision/GeoDMS/assets/48675272/9709114e-ff96-4479-87bb-c06828290d12)

The above code results in the following (working) background layer and almost properly reprojected grid.

**Comment by jipclaassens** [comment]
The above works whereas the initial setting of DialogData to domain did not, the spatial reference is not properly retrieved from domain. Further investigation necessary to see why this is the case.

**Comment by eoudejans** [comment]
The following does not work, which is working as intended:

```cpp
unit<ipoint> UrbanArea_StartYear_dd_domain
: storagename = "= propvalue(Store_UrbanArea_StartYear, 'StorageName')"
, StorageType     = "gdal.grid"
, StorageReadOnly = "True"
, DialogData = "domain"
{
	attribute<float32> GridData;
	attribute<float32> ReadData (domain);
} 
```

This does not work because domain is not necessary a BaseProjection, but can be for instance a rdc100m gridset. Therefore the desired route in this case is the proposed usage of BaseProjection Geography/LatLong for DialogData property.

**Comment by eoudejans** [comment]
What should be added however is a warning that notifies the user that the grid that is about to be read in cannot be mapped to more than 50% percent of the domain using ReadData.

**Comment by eoudejans** [comment]
![image](https://github.com/ObjectVision/GeoDMS/assets/96182097/9bb8e7bf-7a55-45ad-b98f-e649cac0686e)
