### ISSUE TITLE
crash op gui export naar shapefile

### ISSUE THREAD

**Issue by jipclaassens** [ObjectVision/GeoDMS#7]
rechtermuis knop > export > dbf and shp op attribuut, dan opslaan geeft freeze en error:

"device or resource busy: device or resource busy
/Desktops/Default/ViewData/DbfTable"

het is een vector attribuut, maar de geometry is niet daar geconfigureerd. Wanneer je het eerst een unit configureert, en dan rechtermuisknop op de unit werkt wel. Dat is mogelijk ook wenselijk gedrag. Desondanks zou de crash, error en freeze niet moeten komen. 
Of wil je niet toestaan dat je een attribuut zo kunt exporteren?

OVSRV06:
C:\ProjDir\Jip\LUS_FTM_issueGH7\cfg\main.dms

export op: /Analysis/Allocatie/Per_AllocRegios/StartingState/RestClaim

gebeurt in 8.6.3

**Comment by eoudejans** [comment]
@jipclaassens Reproducibility confirmed. 

Alternative way to reproduce:
1. Clone https://github.com/ObjectVision/GeoDMS-Test
2. Open GeoDMS-Test/Storage_gdal/regression.dms in gui
3. Right-click item /csv/read/src/comma/id >> Export Primary Data >> Table "..."

**Comment by MaartenHilferink** [comment]
Fixed in next v8.6.3.
"C:\LocalData\LUS_FTM_issueGH7\Results\main\Analysis_Allocatie_Per_AllocRegios_StartingState_RestClaim.DBF" is now created, without corresponding .shp, but when geography/Gemeente gets DialogData = "geometry", DialogType = "Map", a related .shp is created; the attribute geometry is not yet recognized as feature-attribute automatically.
